apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-vikas
  labels:
    app: tts-vikas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts-vikas
  template:
    metadata:
      labels:
        app: tts-vikas
    spec:
      containers:
      - name: tts-vikas
        image: mansri123/tts-server:v2
        ports:
        - name: http-port
          containerPort: 9069

---

apiVersion: v1
kind: Service
metadata:
  name: tts-vikas-svc
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
  selector:
    app: tts-vikas